# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
if Team.all.length < 32
  Team.create!(location:'Arizona', team_name:'Cardinals')
  Team.create!(location:'Atlanta', team_name:'Falcons')
  Team.create!(location:'Baltimore', team_name:'Ravens')
  Team.create!(location:'Buffalo', team_name:'Bills')
  Team.create!(location:'Carolina', team_name:'Panthers')
  Team.create!(location:'Chicago', team_name:'Bears')
  Team.create!(location:'Cincinnati', team_name:'Bengals')
  Team.create!(location:'Cleveland', team_name:'Browns')
  Team.create!(location:'Dallas', team_name:'Cowboys')
  Team.create!(location:'Denver', team_name:'Broncos')
  Team.create!(location:'Detroit', team_name:'Lions')
  Team.create!(location:'Green Bay', team_name:'Packers')
  Team.create!(location:'Houston', team_name:'Texans')
  Team.create!(location:'Indianapolis', team_name:'Colts')
  Team.create!(location:'Jacksonville', team_name:'Jaguars')
  Team.create!(location:'Kansas City', team_name:'Chiefs')
  Team.create!(location:'Miami', team_name:'Dolphins')
  Team.create!(location:'Minnesota', team_name:'Vikings')
  Team.create!(location:'New England', team_name:'Patriots')
  Team.create!(location:'New Orleans', team_name:'Saints')
  Team.create!(location:'New York', team_name:'Giants')
  Team.create!(location:'New York', team_name:'Jets')
  Team.create!(location:'Oakland', team_name:'Raiders')
  Team.create!(location:'Philadelphia', team_name:'Eagles')
  Team.create!(location:'Pittsburgh', team_name:'Steelers')
  Team.create!(location:'Los Angeles', team_name:'Chargers')
  Team.create!(location:'San Francisco', team_name:'49ers')
  Team.create!(location:'Seattle', team_name:'Seahawks')
  Team.create!(location:'Los Angeles', team_name:'Rams')
  Team.create!(location:'Tampa Bay', team_name:'Buccaneers')
  Team.create!(location:'Tennessee', team_name:'Titans')
  Team.create!(location:'Washington', team_name:'Redskins')
end
