# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
if Team.all.length < 32
  Team.create!(location:'Arizona', team_name:'Cardinals')
  Team.create!(location:'Atlanta', team_name:'Falcons')
  Team.create!(location:'Baltimore', team_name:'Ravens')
  Team.create!(location:'Buffalo', team_name:'Bills')
  Team.create!(location:'Carolina', team_name:'Panthers')
  Team.create!(location:'Chicago', team_name:'Bears')
  Team.create!(location:'Cincinnati', team_name:'Bengals')
  Team.create!(location:'Cleveland', team_name:'Browns')
  Team.create!(location:'Dallas', team_name:'Cowboys')
  Team.create!(location:'Denver', team_name:'Broncos')
  Team.create!(location:'Detroit', team_name:'Lions')
  Team.create!(location:'Green Bay', team_name:'Packers')
  Team.create!(location:'Houston', team_name:'Texans')
  Team.create!(location:'Indianapolis', team_name:'Colts')
  Team.create!(location:'Jacksonville', team_name:'Jaguars')
  Team.create!(location:'Kansas City', team_name:'Chiefs')
  Team.create!(location:'Miami', team_name:'Dolphins')
  Team.create!(location:'Minnesota', team_name:'Vikings')
  Team.create!(location:'New England', team_name:'Patriots')
  Team.create!(location:'New Orleans', team_name:'Saints')
  Team.create!(location:'New York', team_name:'Giants')
  Team.create!(location:'New York', team_name:'Jets')
  Team.create!(location:'Oakland', team_name:'Raiders')
  Team.create!(location:'Philadelphia', team_name:'Eagles')
  Team.create!(location:'Pittsburgh', team_name:'Steelers')
  Team.create!(location:'Los Angeles', team_name:'Chargers')
  Team.create!(location:'San Francisco', team_name:'49ers')
  Team.create!(location:'Seattle', team_name:'Seahawks')
  Team.create!(location:'Los Angeles', team_name:'Rams')
  Team.create!(location:'Tampa Bay', team_name:'Buccaneers')
  Team.create!(location:'Tennessee', team_name:'Titans')
  Team.create!(location:'Washington', team_name:'Redskins')
end

if Week.all.length < 17
  Week.create!(week_number:1, year:2017, start_date:Date.new(2017,9,1), end_date:Date.new(2017,9,12))
  Week.create!(week_number:2, year:2017, start_date:Date.new(2017,9,13), end_date:Date.new(2017,9,19))
  Week.create!(week_number:3, year:2017, start_date:Date.new(2017,9,20), end_date:Date.new(2017,9,26))
  Week.create!(week_number:4, year:2017, start_date:Date.new(2017,9,27), end_date:Date.new(2017,10,3))
  Week.create!(week_number:5, year:2017, start_date:Date.new(2017,10,4), end_date:Date.new(2017,10,10))
  Week.create!(week_number:6, year:2017, start_date:Date.new(2017,10,11), end_date:Date.new(2017,10,17))
  Week.create!(week_number:7, year:2017, start_date:Date.new(2017,10,18), end_date:Date.new(2017,10,24))
  Week.create!(week_number:8, year:2017, start_date:Date.new(2017,10,25), end_date:Date.new(2017,10,31))
  Week.create!(week_number:9, year:2017, start_date:Date.new(2017,11,1), end_date:Date.new(2017,11,7))
  Week.create!(week_number:10, year:2017, start_date:Date.new(2017,11,8), end_date:Date.new(2017,11,14))
  Week.create!(week_number:11, year:2017, start_date:Date.new(2017,11,15), end_date:Date.new(2017,11,21))
  Week.create!(week_number:12, year:2017, start_date:Date.new(2017,11,22), end_date:Date.new(2017,11,28))
  Week.create!(week_number:13, year:2017, start_date:Date.new(2017,11,29), end_date:Date.new(2017,12,5))
  Week.create!(week_number:14, year:2017, start_date:Date.new(2017,12,6), end_date:Date.new(2017,12,12))
  Week.create!(week_number:15, year:2017, start_date:Date.new(2017,12,13), end_date:Date.new(2017,12,19))
  Week.create!(week_number:16, year:2017, start_date:Date.new(2017,12,20), end_date:Date.new(2017,12,26))
  Week.create!(week_number:17, year:2017, start_date:Date.new(2017,12,27), end_date:Date.new(2018,1,1))
end

if Week.current_week.nil?
  Week.create!(week_number:1, year:2018, start_date:Date.new(2018,1,1), end_date:Date.new(2018,6,30))
  Game.create!(week_id:Week.current_week.id, away_team_id: 1, home_team_id:2)
  Game.create!(week_id:Week.current_week.id, away_team_id: 3, home_team_id:4)
  Game.create!(week_id:Week.current_week.id, away_team_id: 5, home_team_id:6)
  Game.create!(week_id:Week.current_week.id, away_team_id: 7, home_team_id:8)
  Game.create!(week_id:Week.current_week.id, away_team_id: 9, home_team_id:10)
  Game.create!(week_id:Week.current_week.id, away_team_id: 11, home_team_id:12)
  Game.create!(week_id:Week.current_week.id, away_team_id: 13, home_team_id:14)
  Game.create!(week_id:Week.current_week.id, away_team_id: 15, home_team_id:16)
  Game.create!(week_id:Week.current_week.id, away_team_id: 17, home_team_id:18)
  Game.create!(week_id:Week.current_week.id, away_team_id: 19, home_team_id:20)
  Game.create!(week_id:Week.current_week.id, away_team_id: 21, home_team_id:22)
  Game.create!(week_id:Week.current_week.id, away_team_id: 23, home_team_id:24)
  Game.create!(week_id:Week.current_week.id, away_team_id: 25, home_team_id:26)
  Game.create!(week_id:Week.current_week.id, away_team_id: 27, home_team_id:28)
  Game.create!(week_id:Week.current_week.id, away_team_id: 29, home_team_id:30)
  Game.create!(week_id:Week.current_week.id, away_team_id: 31, home_team_id:32)
end
